experimentName: mnist
trialConcurrency: 1
maxExperimentDuration: 1h
maxTrialNumber: 10
searchSpaceFile: search_space.json
useAnnotation: false
trialCommand: python main.py
trialCodeDirectory: .
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
